#!/bin/sh
export SDLMIXER_INSTALL_DIR=./usr
#export CEGUI_INSTALL_DIR=/u/ruoyi/CEGUI-0.7.6
export PKG_CONFIG_PATH=${SDLMIXER_INSTALL_DIR}/lib/pkgconfig
rm -rf autom4te.cache
libtoolize --force --copy &&  aclocal &&  autoheader &&  automake --add-missing --force-missing --copy --foreign &&  autoconf
./configure && ./makeit
