#!/bin/sh
export BULLET_INSTALL_DIR=./bullet-2.79
export PKG_CONFIG_PATH=${BULLET_INSTALL_DIR}/lib/pkgconfig
rm -rf autom4te.cache
libtoolize --force --copy &&  aclocal &&  autoheader &&  automake --add-missing --force-missing --copy --foreign &&  autoconf
./configure && ./makeit
